"""Deterministic, content-free answer-quality evaluation for WL-300.5.

This is intentionally separate from retrieval scoring.  It accepts answers
already generated by a caller, compares them in memory against the admitted
LongMemEval references, and returns aggregate metrics plus digests only.  It
does not generate answers, invoke an LLM, expose questions/references/answers,
or mutate BHM, SQLite, Qdrant, or Mem0.
"""

from __future__ import annotations

from collections import Counter
from collections.abc import Mapping
import hashlib
import re
from pathlib import Path
from typing import Any

from .external_evaluation_admission import ExternalEvaluationAdmissionError
from .external_evaluation_admission import verify_external_evaluation_admission_report
from .longmemeval_smoke import _category
from .longmemeval_smoke import _digest
from .longmemeval_smoke import _load_dataset
from .longmemeval_smoke import _select_cases
from .longmemeval_smoke import _text
from .memory_evaluation import MAX_SMOKE_CASES


SCHEMA_VERSION = "bhm.longmemeval.answer-quality.v1"
_TOKEN_RE = re.compile(r"[A-Za-z0-9_]{1,64}")
_MAX_ANSWER_CHARS = 20_000


class LongMemEvalAnswerQualityError(ValueError):
    """Raised when a bounded answer-evaluation input is incomplete or unsafe."""


def _normalised_tokens(value: str) -> tuple[str, ...]:
    return tuple(token.casefold() for token in _TOKEN_RE.findall(value))


def _token_f1(expected: str, actual: str) -> float:
    expected_tokens = _normalised_tokens(expected)
    actual_tokens = _normalised_tokens(actual)
    if not expected_tokens and not actual_tokens:
        return 1.0
    if not expected_tokens or not actual_tokens:
        return 0.0
    overlap = sum((Counter(expected_tokens) & Counter(actual_tokens)).values())
    if not overlap:
        return 0.0
    precision = overlap / len(actual_tokens)
    recall = overlap / len(expected_tokens)
    return 2 * precision * recall / (precision + recall)


def _normalised_exact_match(expected: str, actual: str) -> bool:
    return _normalised_tokens(expected) == _normalised_tokens(actual)


def _validated_answers(
    answers: Mapping[str, object] | None,
    *,
    expected_case_ids: tuple[str, ...],
) -> dict[str, str] | None:
    if answers is None:
        return None
    if not isinstance(answers, Mapping):
        raise LongMemEvalAnswerQualityError("generated_answers must be a mapping of case IDs to bounded strings")
    normalised: dict[str, str] = {}
    for raw_case_id, raw_answer in answers.items():
        case_id = _text(raw_case_id, "generated_answer.case_id")
        if not isinstance(raw_answer, str):
            raise LongMemEvalAnswerQualityError("generated answer must be a string")
        answer = raw_answer.strip()
        if len(answer) > _MAX_ANSWER_CHARS:
            raise LongMemEvalAnswerQualityError("generated answer exceeds the bounded answer limit")
        normalised[case_id] = answer
    expected = set(expected_case_ids)
    actual = set(normalised)
    if actual != expected:
        raise LongMemEvalAnswerQualityError("generated answers must cover each selected case exactly once")
    return normalised


def _reference_answer(value: object) -> str:
    """Normalise the two scalar label forms admitted by LongMemEval-S.

    Most cases use an answer string, while a small subset of temporal,
    multi-session and knowledge-update cases uses an integer label.  Treat the
    latter as its canonical decimal text for deterministic Exact Match/F1;
    arrays and other structures remain fail-closed.
    """

    if isinstance(value, bool):
        raise LongMemEvalAnswerQualityError("LongMemEval answer must be a bounded string or integer")
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str) and len(value.strip()) <= _MAX_ANSWER_CHARS:
        return value.strip()
    raise LongMemEvalAnswerQualityError("LongMemEval answer must be a bounded string or integer")


def evaluate_longmemeval_answer_quality(
    dataset_path: str | Path,
    *,
    dataset_version: str,
    admission_report: Mapping[str, Any],
    generated_answers: Mapping[str, object] | None = None,
    max_cases: int = MAX_SMOKE_CASES,
    split_index: int = 0,
) -> dict[str, Any]:
    """Evaluate caller-supplied answers against an admitted local dataset.

    Omitting ``generated_answers`` is supported and deliberately returns an
    explicit ``not_evaluated`` state.  A retrieval-only run must never be
    relabelled as answer quality.
    """

    try:
        admission = verify_external_evaluation_admission_report(dict(admission_report))
    except ExternalEvaluationAdmissionError as exc:
        raise LongMemEvalAnswerQualityError("LongMemEval admission report is invalid") from exc
    if admission["dataset"]["suite"] != "longmemeval" or admission["dataset"]["version"] != dataset_version:
        raise LongMemEvalAnswerQualityError("admission report does not match the requested LongMemEval dataset")
    items, dataset_digest = _load_dataset(dataset_path)
    if admission["dataset"]["dataset_digest"] != dataset_digest:
        raise LongMemEvalAnswerQualityError("admission report digest does not match local dataset")

    selected = _select_cases(items, max_cases=max_cases, split_index=split_index)
    references: dict[str, str] = {}
    categories: dict[str, str] = {}
    for item in selected:
        case_id = _text(item.get("question_id"), "question_id")
        references[case_id] = _reference_answer(item.get("answer"))
        categories[case_id] = _category(item)

    case_ids = tuple(sorted(references))
    answers = _validated_answers(generated_answers, expected_case_ids=case_ids)
    reference_digest = _digest(
        {case_id: hashlib.sha256(references[case_id].encode("utf-8")).hexdigest() for case_id in case_ids}
    )
    common = {
        "schema_version": SCHEMA_VERSION,
        "suite": "longmemeval",
        "dataset_version": dataset_version,
        "dataset_digest": dataset_digest,
        "admission_digest": admission["admission_digest"],
        "case_split_index": split_index,
        "reference_contract": {
            "case_count": len(case_ids),
            "reference_digest": reference_digest,
            "raw_reference_returned": False,
        },
        "execution": {
            "network": False,
            "model_calls": 0,
            "sqlite_mutation": False,
            "qdrant_mutation": False,
            "mem0_mutation": False,
            "runtime_feature_enabled": False,
            "raw_answer_returned": False,
        },
    }
    if answers is None:
        result = {
            **common,
            "answer_quality": {
                "status": "not_evaluated",
                "reason": "no_generated_answers_supplied",
                "scored_case_count": 0,
                "exact_match": None,
                "token_f1": None,
                "abstention_exact_match": None,
            },
        }
    else:
        f1_scores = [_token_f1(references[case_id], answers[case_id]) for case_id in case_ids]
        exact_scores = [_normalised_exact_match(references[case_id], answers[case_id]) for case_id in case_ids]
        abstention_case_ids = tuple(case_id for case_id in case_ids if categories[case_id] == "abstention")
        abstention_scores = [
            _normalised_exact_match(references[case_id], answers[case_id]) for case_id in abstention_case_ids
        ]
        result = {
            **common,
            "generated_answer_contract": {
                "case_count": len(case_ids),
                "generated_answer_digest": _digest(
                    {case_id: hashlib.sha256(answers[case_id].encode("utf-8")).hexdigest() for case_id in case_ids}
                ),
                "raw_answer_returned": False,
            },
            "answer_quality": {
                "status": "complete",
                "scored_case_count": len(case_ids),
                "exact_match": round(sum(exact_scores) / len(exact_scores), 6),
                "token_f1": round(sum(f1_scores) / len(f1_scores), 6),
                "abstention_exact_match": (
                    round(sum(abstention_scores) / len(abstention_scores), 6) if abstention_scores else None
                ),
            },
        }
    result["report_digest"] = _digest({key: value for key, value in result.items() if key != "report_digest"})
    return result


__all__ = ["LongMemEvalAnswerQualityError", "SCHEMA_VERSION", "evaluate_longmemeval_answer_quality"]
